### ISSUE TITLE
How do you set it up so it only runs on staging or prod?

### ISSUE THREAD

**Issue by arun057** [Kikobeats/sails-hook-newrelic#5]
Tried setting the license key in my local.js file but it looks like it doesnt wait for sails config to load.

**Comment by Kikobeats** [comment]
check the new version, maybe now you can set a different behavior between envs:
https://github.com/Kikobeats/sails-hook-newrelic/compare/0.2.1...0.2.2

**Comment by arun057** [comment]
Same thing with the new version.

```
New Relic for Node.js halted startup due to an error:
Error: Invalid license key, please contact support@newrelic.com
    at StreamSink.parser [as callback] (...releases/20150324155459/node_modules/newrelic/lib/collector/parse-response.js:81:25)
    at StreamSink.end (...releases/20150324155459/node_modules/newrelic/lib/util/stream-sink.js:43:8)
    at IncomingMessage.onend (_stream_readable.js:505:10)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at wrapped (...releases/20150324155459/node_modules/newrelic/lib/transaction/tracer/index.js:156:28)
    at _tickDomainCallback (node.js:381:11)
    at process.nextTickWrapper (...releases/20150324155459/node_modules/newrelic/lib/instrumentation/core/timers.js:12:14)
```

**Comment by arun057** [comment]
My `config/newrelic.js` has:

```
module.exports.newrelic = {
  logging: {
    level: 'warn', // can be error, warn, info, debug or trace
    rules: {
      ignore: ['^/socket.io/*/xhr-polling']
    }
  }
};
```

`local.js` has

```
module.exports = {
  newrelic: {
    app_name: ['my app name'],
    license_key: 'my long license key.' // with the key in there
  }
}
```

**Comment by fridaystreet** [comment]
Was also looking for a solution to handle this. I just modified the register.js as follows

```
var env = process.env.NODE_ENV;
var configFile = 'config/newrelic';
if(env){
  configFile = 'config/env/' + env;
}
var config = require(path.resolve(configFile)).newrelic;
```

Then you can just add the newrelic config to each of your environment config files respectively (config/env/production.js, development.js etc) 

Happy to submit a pull request if kikobeats is open to it.

**Comment by Kikobeats** [comment]
@fridaystreet Make a PR and the contributors decide if will be merged :-)

**Comment by fridaystreet** [comment]
@Kikobeats no worries thanks, I added a pull request today. https://github.com/Kikobeats/sails-hook-newrelic/pull/9

Nice work on the module btw, very useful over the standard newrelic one.

**Comment by kopylash** [comment]
added this in 0.3.0
